version: '3'
services:

  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    container_name: dremio
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    ports:  
      - 9047:9047 
      - 31010:31010 
      - 45678:45678
      - 32010:32010
    volumes:
      - dremio:/opt/dremio/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  jupyter:
      build: ./jupyter/
      environment:
        - S3_ENDPOINT=http://minio:9000
        - S3_BUCKET=test
        - S3_ACCESS_KEY=accesskey
        - S3_SECRET_KEY=secretkey
      ports: 
        - 8888:8888
      volumes:
        - ./data:/data
        - ./jupyter/notebooks/:/notebooks/
  minio:
    image: quay.io/minio/minio
    command: ["server", "/data", "--console-address", ":9090"]
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio-data:/data
    ports:
      - 9090:9090
      - 9000:9000
  minio-init:
    build: ./minio # MinioClient image; use it to make buckets and perform any other tasks on startup
    depends_on:
      - minio

networks:
  intro-network:
    driver: bridge
 
volumes:
  dremio:
  minio-data:
